# Generated by Django 5.2.6 on 2026-01-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
