# Generated by Django 5.2.6 on 2026-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
