# Generated by Django 5.2.6 on 2026-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accounts_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='company_logo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='employer_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
