# Generated by Django 5.2.6 on 2026-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_accounts_address_alter_accounts_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='avatar',
            field=models.CharField(blank=True, default='https://static.vecteezy.com/system/resources/previews/026/434/417/original/default-avatar-profile-icon-of-social-media-user-photo-vector.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='company_logo',
            field=models.CharField(blank=True, default='https://static.vecteezy.com/system/resources/previews/026/434/417/original/default-avatar-profile-icon-of-social-media-user-photo-vector.jpg', max_length=255, null=True),
        ),
    ]
